version: '3.8'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=127.0.0.1
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - "8081:80"
    restart: unless-stopped
